# Site
repository: richrookie/resume
favicon: images/favicon.ico

version: 2

# Personal info
name: 최영민
title: 게임 클라이언트 개발자
email: psymchoi@gmail.com
website: https://richrookie.github.io/

# Social links
github_username:  richrookie
linkedin_username: youngmin-choi-bs-2405b6208
stackoverflow_username: "23053463"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpeg
about_content: |

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# OpenSource Section
# experience_title: OpenSource

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

# sass:
#   style: compressed
