# Site
repository: richrookie/resume
favicon: images/favicon.ico

version: 2

# Personal info
name: 최 영민
title: 클라이언트 개발자
email: psymchoi@gmail.com
website: https://richrookie.github.io/

# Social links
github_username:  richrookie
linkedin_username: youngmin-choi-bs-2405b6208
stackoverflow_username: "23053463"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpeg
about_content: |
  # <mark>git</mark> 


# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# OpenSource Section
# experience_title: OpenSource

# Education Section
# educaton_title: Education


content:
  - title: Projects # Title for the section
    layout: list
    content:
      - layout: top-middle
        border: weak
        title: Modern Resume Theme
        link: sproogen.github.io/modern-resume-theme
        additional_links:
          - title: sproogen/modern-resume-theme
            icon: fab fa-github
            url: https://github.com/sproogen/modern-resume-theme
        quote: >
          A modern simple static resume template and theme. Powered by Jekyll and GitHub pages.
        description: |
          This is a <mark>Jekyll</mark> theme that I have recently created, in fact it is what this resume has been built with.
          I decided I wanted to learn how to create a fully open source project and thought that this would be the perfect project to do this with.
          It has allowed me to share something I have created in a way that will be helpful for lots of people while also learning from this myself.
      - layout: top-middle
        title: itsgoingto.be
        link: www.itsgoingto.be
        additional_links:
          - title: sproogen/itsgoingto.be
            icon: fab fa-github
            url: https://github.com/sproogen/itsgoingto.be
        quote: >
          itsgoingto.be is a simple voting site where a user can ask a question or topic top put to a vote. This question
          can then be shared with their friends/colleagues to vote on things like 'Where should we go for lunch?'.
        description: |
          The API for this site has been build using <mark>Node.js</mark> while the front end is a <mark>React</mark>/<mark>Redux</mark> app.
          I have used <mark>Docker</mark> to set up a development environment and <mark>Heroku</mark> to deploy and host the site. I have
          a suite of unit and API tests for the backend and unit tests for the front end.

          I have been using this project as a way to increase many of my skills and also learn new things, most recently sockets and Node.JS. I have particually
          enjoyed managing my own project and designing my own architecture and implementing this to a high standard.

          Feel free to check out the whole project on GitHub to get a feel for how I work [here](https://github.com/sproogen/itsgoingto.be).

  - title: Experience
    layout: list
    content:
      - layout: left
        border: weak
        title: MondayOFF
        link: https://www.mondayoff.me/
        sub_title: 클라이언트 개발자
        caption: 2020.10 - Present
        description: |
        

    
  - title: Education
    layout: list
    content:
      - title: 상명대학교
        sub_title: BSc 정보통신공학과
        caption: 2014 - 2020
        description: |
         
  - title: When I'm Not Programming
    layout: text
    content: | # this will include new lines to allow paragraphs
   
# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

# sass:
#   style: compressed
