# Site
repository: richrookie/resume
favicon: images/favicon.ico

version: 2

# Personal info
name: 최영민
title: 게임 클라이언트 개발자
email: psymchoi@gmail.com
website: https://richrookie.github.io/

# Social links
github_username:  richrookie
linkedin_username: youngmin-choi-bs-2405b6208
# stackoverflow_username: "23053463"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: |
  **Unity Engine**을 활용한 **4년 차** 게임 클라이언트 개발자로
  **6억원**의 매출과 누적 유저수**300만** 등의 서비스를 제공하였고, 전반적인 게임 개발과 개발 환경을 개선해왔습니다.<br/>
  스타트업에서 발생할 수 있는 여러 문제를 직면하면서 회사와 팀에 도움이 되기 위하여 노력했습니다. 
  대표적으로 <mark>Unity Framework</mark>를 제공함으로써 인하우스 내 개발 환경을 **100%** 개선하였고, 
  제작과정에서 혼선을 해결하기 위하여 <mark>Notion</mark>정리를 추진하여 **80%** 이상 실수를 방지시켰습니다.<br/>
  현재는 클라이언트 개발자로서 **기획 설계**부터 **제작과정**과 **팀 매니징**을 주요 업무로 하고 있습니다.
# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# OpenSource Section
# experience_title: OpenSource

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

# sass:
#   style: compressed
